// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz7EArrmHUlw6-i-O0NKrgS2DXZ8Ti9HY',
    appId: '1:597499278453:web:3eeffe692165d718ecf43c',
    messagingSenderId: '597499278453',
    projectId: 'turf11-dac3b',
    authDomain: 'turf11-dac3b.firebaseapp.com',
    storageBucket: 'turf11-dac3b.firebasestorage.app',
    measurementId: 'G-GWRKY970MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuzRayKFcFJ3vDdJ0JbNXVboNFDYYR1ME',
    appId: '1:597499278453:android:d98d51138436d9b9ecf43c',
    messagingSenderId: '597499278453',
    projectId: 'turf11-dac3b',
    storageBucket: 'turf11-dac3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9sI7PM9B140Atc4xR5HR0kd2K0Gsn7oI',
    appId: '1:597499278453:ios:28550b5f724ac413ecf43c',
    messagingSenderId: '597499278453',
    projectId: 'turf11-dac3b',
    storageBucket: 'turf11-dac3b.firebasestorage.app',
    iosBundleId: 'turf11.book.play',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9sI7PM9B140Atc4xR5HR0kd2K0Gsn7oI',
    appId: '1:597499278453:ios:96a3fbb99ff27d53ecf43c',
    messagingSenderId: '597499278453',
    projectId: 'turf11-dac3b',
    storageBucket: 'turf11-dac3b.firebasestorage.app',
    iosBundleId: 'com.example.flutterTurf11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz7EArrmHUlw6-i-O0NKrgS2DXZ8Ti9HY',
    appId: '1:597499278453:web:5661cedec5842a25ecf43c',
    messagingSenderId: '597499278453',
    projectId: 'turf11-dac3b',
    authDomain: 'turf11-dac3b.firebaseapp.com',
    storageBucket: 'turf11-dac3b.firebasestorage.app',
    measurementId: 'G-3FTL84BFC0',
  );

}